BlockCrafting.addMultiblockStructure(
    MultiblockStructureBuilder.create("test:multi3")
        .pattern('aaa', 'aaa', 'aaa')
        .pattern('aaa', 'aba', 'aaa')
        .pattern('aaa', 'aaa', 'aaa')
        .center('a', 'minecraft:cobblestone')
        .where('b', 'minecraft:redstone_block')
        .craftingItemTag("forge:ingots")
        .resultItem(MC("diamond", 2))
        // .resultEntity("minecraft:blaze")
        .resultAction((level, pos, player) => {
            var item = player.getMainHandItem()
            item.shrink(1)
        })
        .build()
)
ItemEvents.rightClicked(MC('dirt'), event => {
    let tt = MultiblockStructureBuilder.create("test:multi3")
        .pattern('aaa', 'aaa', 'aaa')
        .pattern('aaa', 'aba', 'aaa')
        .pattern('aaa', 'aaa', 'aaa')
        .center('a', 'minecraft:cobblestone')
        .where('b', 'minecraft:redstone_block')
        .craftingItemTag("forge:ingots")
        .resultItem(MC("diamond", 2))
        // .resultEntity("minecraft:blaze")
        .resultAction((level, pos, player) => {
            var item = player.getMainHandItem()
            item.shrink(1)
        })
        .build()
    console.log(tt)
})
